input: /home/hovakim/GitSync/main/nf-core-quickflow/test_data/compounds.csv
outdir: /home/hovakim/GitSync/main/nf-core-quickflow/testOut


singularity_local_container: /home/hovakim/GitSync/quick.sif
singularity_use_local_file: true
singularity_pull_docker_container: false


libxc: function1,function2
useGPU: false
export: null

# basis: "STO-3G"
# basis: "6-311+G(2d,p)"

# basis: "STO-YOLO"

# method: DFT
# basis: 6G
# optimize: true/false
# export_molden: true/false